name: Simple-Django-Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        - name: Check secrets
          run: | 
            echo "HOST is set: ${{ secrets.HOST != '' }}"
            echo "KEY is set: ${{ secrets.EC2_SSH_KEY != '' }}"


      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            set -e
            cd ~/django-cicd-demo
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
